apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: default
data:
  index.html: |
    Ini tampilan dari NGINX dan nama saya dahnur
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-nginx
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-nginx
  template:
    metadata:
      labels:
        app: simple-nginx
    spec:
      containers:
      - name: nginx
        image: nginx:stable
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-html
          mountPath: /usr/share/nginx/html
      volumes:
      - name: nginx-html
        configMap:
          name: nginx-config
          items:
          - key: index.html
            path: index.html
---
apiVersion: v1
kind: Service
metadata:
  name: simple-nginx
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: simple-nginx
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: httpd-config
  namespace: default
data:
  index.html: |
    Ini tampilan dari HTTPD dan nama saya dahnur
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-httpd
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-httpd
  template:
    metadata:
      labels:
        app: simple-httpd
    spec:
      containers:
      - name: httpd
        image: httpd:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: httpd-html
          mountPath: /usr/local/apache2/htdocs
      volumes:
      - name: httpd-html
        configMap:
          name: httpd-config
          items:
          - key: index.html
            path: index.html
---
apiVersion: v1
kind: Service
metadata:
  name: simple-httpd
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: simple-httpd
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

